#! /bin/sh -eux
# Script based on: https://tesser.org/doc/posts/2015-08-21-statically-linking-libgmp-in-haskell-programs.html

# Remove some libs from dynamic linking
CCARGS=$(echo "$@" | sed -e 's/-lfann//g;s/-ldoublefann//g;s/-lpng//g;s/-lgmp//g')


#Paths to static libraries
LIBDIR_="/usr/lib/x86_64-linux-gnu/"
FANN=${LIBDIR_}libfann.a
FANND=${LIBDIR_}libdoublefann.a
PNG=${LIBDIR_}libpng12.a
GMP=${LIBDIR_}libgmp.a
FLTK_PATH="/app/.cabal-sandbox/lib/x86_64-linux-ghc-7.8.4/fltkhs-0.3.0.1/libfltkc.a"
FLTK="-Wl,--whole-archive -Wl,-Bstatic -Wl,$FLTK_PATH -Wl,-Bdynamic -Wl,--no-whole-archive"

# modified gcc command, static libraries at the end
gcc $FLTK $CCARGS $FANN $FANND $PNG $GMP
